module.exports = {
  mode: 'jit',
  purge: [
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-inter)', 'sans-serif'],
        display: ['var(--font-manrope)', 'sans-serif'],
      },
      colors: {
        background: '#0c141b',
        error: '#ffb4ab',
        error_container: '#93000a',
        inverse_on_surface: '#293139',
        inverse_primary: '#00696e',
        inverse_surface: '#dbe3ed',
        on_background: '#dbe3ed',
        on_error: '#690005',
        on_error_container: '#ffdad6',
        on_primary: '#003739',
        on_primary_container: '#002f32',
        on_primary_fixed: '#002022',
        on_primary_fixed_variant: '#004f53',
        on_secondary: '#0e3252',
        on_secondary_container: '#9cbbe2',
        on_secondary_fixed: '#001d36',
        on_secondary_fixed_variant: '#29496a',
        on_surface: '#dbe3ed',
        on_surface_variant: '#bdc9c9',
        on_tertiary: '#3d2f00',
        on_tertiary_container: '#4e3d00',
        on_tertiary_fixed: '#241a00',
        on_tertiary_fixed_variant: '#574400',
        outline: '#879393',
        outline_variant: '#3e4949',
        border_ghost: 'rgba(116, 213, 220, 0.15)', // primary at 15%
        border_ghost_hover: 'rgba(116, 213, 220, 0.3)', // primary at 30%
        primary: '#74d5dc',
        primary_container: '#379fa5',
        primary_fixed: '#91f2f8',
        primary_fixed_dim: '#74d5dc',
        secondary: '#aac9f1',
        secondary_container: '#2c4b6c',
        secondary_fixed: '#d1e4ff',
        secondary_fixed_dim: '#aac9f1',
        surface: '#0c141b',
        surface_bright: '#323a42',
        surface_container: '#182028',
        surface_container_high: '#232b32',
        surface_container_highest: '#2e363d',
        surface_container_low: '#141c23',
        surface_container_lowest: '#070f16',
        surface_dim: '#0c141b',
        surface_tint: '#74d5dc',
        surface_variant: '#2e363d',
        tertiary: '#e8c350',
        tertiary_container: '#cba737',
        tertiary_fixed: '#ffe08a',
        tertiary_fixed_dim: '#e8c350',
      },
      boxShadow: {
        'ambient': '0px 0px 32px -8px rgba(41, 73, 106, 0.08)',
        'glass': '0 4px 30px rgba(0, 0, 0, 0.1)',
      },
      backgroundImage: {
        'gradient-primary': 'linear-gradient(135deg, #74d5dc 0%, #379fa5 100%)',
        'gradient-innovation': 'linear-gradient(90deg, #74d5dc 0%, #e8c350 100%)',
      }
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
}
